### PR TITLE
fix(jest-config) Fallback to default Jest config if it's not overriden

### LINKED ISSUE #38: Running without custom Jest configuration isn't possible
If you don't have a `jest.config.js` file, nor a `jest` key in the package.json, Stryker will fail:

    [2018-04-02 20:52:17.345] [INFO] ConfigReader - Using stryker.conf.js in the current working directory.
    /Users/maarten/Projects/hyperion-web/node_modules/stryker-jest-runner/src/configLoaders/DefaultJestConfigLoader.js:16
                throw new Error('Could not read Jest configuration, please provide a jest.config.js file or a jest config in your package.json');

As a work-around, create a `jest.config.js` with just

    {
    }

I don't think this is a nice approach. Maybe we should just let Stryker could handle this situation?

### PR DESCRIPTION
**Pull request by mthmulders**
When Jest config was not overriden (ie., a project uses default Jest settings) Stryker would fail.

Fixes #38

### CODE REVIEW

File: src/configLoaders/DefaultJestConfigLoader.ts [hunk 1]
```diff
@@ -17,7 +17,7 @@ export default class DefaultJestConfigLoader implements JestConfigLoader {
   }
 
   public loadConfig(): JestConfiguration {
-    const jestConfig = this.readConfigFromJestConfigFile() || this.readConfigFromPackageJson();
+    const jestConfig = this.readConfigFromJestConfigFile() || this.readConfigFromPackageJson() || {};
 
     if (!jestConfig) {
       throw new Error('Could not read Jest configuration, please provide a jest.config.js file or a jest config in your package.json');
```
Comment (nicojs) [inline src/configLoaders/DefaultJestConfigLoader.ts]: This can be removed right? This error cannot occur?

Comment (mthmulders) [reply src/configLoaders/DefaultJestConfigLoader.ts]: You're definitely right! Removed these lines...

**Comment by nicojs** [comment]
Released in v0.6

Changelog didn't update correctly, because the name commit was not confirm to the conventional changelog specs.

```
fix(jest-config) Fallback to default Jest config if it's not overriden (#42)
````

should have been

```
fix(jest-config): fallback to default Jest config if it's not overridden (#42)
```
